name: cep_app
description: "A new Flutter project."



environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  mocktail: ^1.0.1
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

dev_dependencies:
  state_notifier_test: ^0.0.10
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

 


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
